fallback = ''
separator = '  | '

[matching]
'' = ''
'discord' = ''
'balena-etcher' = ''
'Chia Blockchain' = ''
'steam' = ''
'/\({6}[0-9]+\)/' = ''
'vlc' = ''
'org.qbittorrent.qBittorrent' = ''
'Thunderbird' = ''
'thunderbird' = ''
'Postman' = ''
'Insomnia' = ''
'Bitwarden' = ''
'Google-chrome' = ''
'google-chrome' = ''
'Chromium' = ''
'Slack' = ''
'Code' = ''
'code-oss' = ''
'jetbrains-studio' = ''
'Spotify' = ''
'GitHub Desktop' = ''
'/(?i)Youtube.*Brave/' = ''
'/(?i)Google.*Brave/' = ''
'/(?i)Facebook.*Brave/' = '󰈌'
'/(?i)Reddit.*Brave/' = ''
'/(?i)r/.*Brave/' = ''
'/(?i)Web Player.*Brave/' = ''
'/(?i)Zimbra.*Brave/' = ''
'/(?i)mail.*Brave/' = ''
'Cider' = ''
'firefox' = ''
'Brave-browser' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'/nvim ?\w*/' = ''
'/vim ?\w*/' = ''
'/openfortivpn ?\w*/' = '󰖂'
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'Alacritty' = ''
'kitty' = ''
'Skype' = ''
'/(?i)Thunar/' = ''
'org.remmina.Remmina' = ''
'file-roller' = ''
'Caprine' = '󰈎'
'com.obsproject.Studio' = ''
'/mpv/' = ''
